### ISSUE TITLE
lighting not working on full blocks

### ISSUE THREAD

**Issue by kosuuqwk** [LambdAurora/LambDynamicLights#199]
**Describe the bug**
light not working right
![image_2023-12-05_023324168](https://github.com/LambdAurora/LambDynamicLights/assets/152913204/487b3d0e-263d-4e48-bf1f-81ffd353989b)
got a little bit of light from outside cuz im right beside a door that leads outside but the torch isnt emitting light on the floor and walls.

**To Reproduce**
1. Go to a dark room
2. hold light source

**Expected behavior**
light to work as shown on screenshots on the website

**Desktop (please complete the following information):**
 - OS: windows 10
 - Minecraft 1.20.2
 - Fabric Loader version [e.g. 0.10.6+build.214]
 - Mods [e.g. fabric-api v0.25.1+build.416-1.16, lambdynamiclights v1.3.2, modmenu v1.14.6+build.31]
 - Version [e.g. 1.3.2]
 - Branch [e.g. mc1.16]

**Comment by SteamRex25** [comment]
I have this exact issue

**Comment by LambdAurora** [comment]
You've disabled smooth lighting, and I'm pretty sure this being a bit darker is due in some way by ambient occlusion.

You can see a similar effect with smooth lighting but it looks less weird since it's isolated to the corners of the blocks.
![image](https://github.com/user-attachments/assets/57a6b64d-c5de-429d-828e-c88e99def582)

And aside that you also can see the same effect when placing a torch in-world!
![image](https://github.com/user-attachments/assets/0299c434-fbbd-43cc-9819-c239afcf8b1c)
