### ISSUE TITLE
Massive performance drop with Nether lava lakes. Room for optimization?

### ISSUE THREAD

**Issue by chrisunfocused** [LambdAurora/LambDynamicLights#21]
Self explanatory more or less. Every lava block in the nether seems to be calculated individually, which causes massive slowdowns.

I did not have this issue with Optifine dynamic lighting. I'm assuming that there is some clever optimization taking place there.
I'm not sure what that would be, but I thought I'd bring it up!

**Comment by LambdAurora** [comment]
Does this happen only with LambDynamicLights?

**Comment by LambdAurora** [comment]
So, I recently thought about this issue again, and my guesses are it's because of chunk rebuilding, fluids in general have some special geometry which increases the difficulty to chunk rebuild efficiently and it's related to #16.

The only fixes are, either use Sodium or Canvas once it has native handheld lighting. With the first chunk rebuilding is not a big issue and the second chunk rebuilding can be avoided in the future.

But globally there's nothing that can be done in this mod (at least for now). We're at the mercy of how lighting works in Minecraft.
