### ISSUE TITLE
Doesnt work without shaders

### ISSUE THREAD

**Issue by 1Grobotron1** [LambdAurora/LambDynamicLights#211]
**Describe the bug**
Literally doesnt work without shaders

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft: 1.20.1
 - Fabric Loader version: 0.92.0 +1.20.1
 - Mods: Screenshot
 - Version: 2.3.1
 - Branch Mc 1.20 i think
![4221710065770731](https://github.com/LambdAurora/LambDynamicLights/assets/153846880/86b5cb10-60ee-44d3-a8d0-ba3b2ed4e869)
![2024-03-10_13 14 56](https://github.com/LambdAurora/LambDynamicLights/assets/153846880/270b8df4-621d-4d7c-a070-0d84454de362)

**Additional context**

**Comment by 1Grobotron1** [comment]
3 weeks

**Comment by LambdAurora** [comment]
Hi,

Please provide proper logs and a proper mod list. This mod list doesn't seem to be from your mods folder as a normal Fabric or Quilt instance would refuse to launch with multiple versions of the same mod. Screenshots are also hard to work from in the case of mod lists because I'm gonna be honest, I'm not good be very happy trying to keep track of the mod list while searching the mods myself.
In the case of shaders providing which shader was used is also important.

Aside from that, most shaders provide themselves some dynamic lighting capabilities for first-person lighting, which I would recommend to use as it will be more performant and will have less bugs with the shader, with the caveat of not being able to use the mod's lighting APIs which means some items will not light up as they should.

As for your latest comment, please be aware that I am not paid to make mods, this is not my job. I already have a busy schedule between my actual work, my classes at university, my hobbies and my own social activities. I do modding in my spare time and lately I have not had much spare time for modding (nor the motivation) so I'd appreciate to not have to deal with time constraint entitlement. Thank you.
