### ISSUE TITLE
[Question] Why use this over OptiFine?

### ISSUE THREAD

**Issue by Feriixu** [LambdAurora/LambDynamicLights#54]
Hey, I just found this mod, but I can't see why I would use this instead of OptiFine, since dynamic lights are already an option like you said yourself.

**Comment by DragonEggBedrockBreaking** [comment]
> 
> Hey, I just found this mod, but I can't see why I would use this instead of OptiFine, since dynamic lights are already an option like you said yourself.

Sodium is a fabric mod which is much better than OptiFine in terms of performance, and actually optimises a lot rather than loading less chunks and having some placebo options. Sodium is focused on performance rather than cosmetics, therefore other alternative mods are required for other OptiFine features to be used with sodium, e.g. dynamic lighting and zoom. Some have issues with sodium, e.g. connected glass, which is being worked on, some are WIP, e.g. shaders, and a couple of smaller resource-pack features are non-existent as of now. I personally use sodium, and some of the alternative mods are actually better than OptiFine features (e.g. LambdaBetterGrass). I can safely say that I do not miss OptiFine!

**Comment by Feriixu** [comment]
Ah, I understand. I'm glad OptiFine gives me enough performance, I wouldnt want to miss out on the shaders and some other features. Thanks for answering do quickly.

**Comment by LambdAurora** [comment]
The reason this mod exists is to give open-source alternatives, but also modularization.

OptiFine is a big package, while my mod and a few others are features that got separated into their own mod to better fit user's needs.

The last reasons are Sodium and compatibility reasons, OptiFine causes lot of compatibility issues with other mods.

**Comment by FlashyReese** [comment]
Shaders will be soon
